### ISSUE TITLE
Польза паттерна Builder

### ISSUE THREAD

**Issue by maked0n** [kgrosul/TP2HW#1]
Для такого объекта нет смысла применять Builder, говорил на предпоследнем и последнем семинаре об этом.
https://github.com/kgrosul/TP2HW/blob/f7425560bf403e4381746d5dcd51ca10f91ba1d3/pizza.h#L11

**Comment by kgrosul** [comment]
@maked0n вроде бы исправлено

**Comment by kgrosul** [comment]
@maked0n, вроде бы исправлено.
